### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by tmontanaro** [FIWARE/tutorials.XACML-Access-Rules#2]
I tried to clone the repository and run `sudo docker-compose up -d` inside the folder.
Then, it seems that everything works but when I try to create a new application in the IdM I find the following error in the log file of the IdM:

```
Mon, 13 May 2019 15:14:20 GMT idm:web-application_controller Error:  { SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`idm`.`role_assignment`, CONSTRAINT `role_assignment_ibfk_4` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE)\n","stream":"stderr","time":"2019-05-13T15:14:20.459844837Z
    at Query.formatError (/opt/fiware-idm/node_modules/sequelize/lib/dialects/mysql/query.js:236:16)\n","stream":"stderr","time":"2019-05-13T15:14:20.459895403Z
    at Query.handler [as onResult] (/opt/fiware-idm/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)\n","stream":"stderr","time":"2019-05-13T15:14:20.459911537Z
    at Query.execute (/opt/fiware-idm/node_modules/mysql2/lib/commands/command.js:30:14)\n","stream":"stderr","time":"2019-05-13T15:14:20.459941499Z
    at Connection.handlePacket (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:455:32)\n","stream":"stderr","time":"2019-05-13T15:14:20.459955538Z
    at PacketParser.onPacket (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:73:18)\n","stream":"stderr","time":"2019-05-13T15:14:20.459969087Z
    at PacketParser.executeStart (/opt/fiware-idm/node_modules/mysql2/lib/packet_parser.js:75:16)\n","stream":"stderr","time":"2019-05-13T15:14:20.459982567Z
    at Socket.\u003canonymous\u003e (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:80:31)\n","stream":"stderr","time":"2019-05-13T15:14:20.459996116Z
    at emitOne (events.js:116:13)\n","stream":"stderr","time":"2019-05-13T15:14:20.460009805Z
    at Socket.emit (events.js:211:7)\n","stream":"stderr","time":"2019-05-13T15:14:20.460022935Z
    at addChunk (_stream_readable.js:263:12)\n","stream":"stderr","time":"2019-05-13T15:14:20.460035647Z
    at readableAddChunk (_stream_readable.js:250:11)\n","stream":"stderr","time":"2019-05-13T15:14:20.460048847Z
    at Socket.Readable.push (_stream_readable.js:208:10)\n","stream":"stderr","time":"2019-05-13T15:14:20.460062117Z
    at TCP.onread (net.js:601:20)\n","stream":"stderr","time":"2019-05-13T15:14:20.460075876Z
  name: 'SequelizeForeignKeyConstraintError',\n","stream":"stderr","time":"2019-05-13T15:14:20.460097597Z
  parent: \n","stream":"stderr","time":"2019-05-13T15:14:20.460115337Z
   { Error: Cannot add or update a child row: a foreign key constraint fails (`idm`.`role_assignment`, CONSTRAINT `role_assignment_ibfk_4` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE)\n","stream":"stderr","time":"2019-05-13T15:14:20.460133147Z
    at Packet.asError (/opt/fiware-idm/node_modules/mysql2/lib/packets/packet.js:684:17)\n","stream":"stderr","time":"2019-05-13T15:14:20.460151795Z
    at Query.execute (/opt/fiware-idm/node_modules/mysql2/lib/commands/command.js:28:26)\n","stream":"stderr","time":"2019-05-13T15:14:20.460169814Z
    at Connection.handlePacket (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:455:32)\n","stream":"stderr","time":"2019-05-13T15:14:20.460187624Z
    at PacketParser.onPacket (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:73:18)\n","stream":"stderr","time":"2019-05-13T15:14:20.460205783Z
    at PacketParser.executeStart (/opt/fiware-idm/node_modules/mysql2/lib/packet_parser.js:75:16)\n","stream":"stderr","time":"2019-05-13T15:14:20.460223872Z
    at Socket.\u003canonymous\u003e (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:80:31)\n","stream":"stderr","time":"2019-05-13T15:14:20.460241891Z
    at emitOne (events.js:116:13)\n","stream":"stderr","time":"2019-05-13T15:14:20.460262076Z
    at Socket.emit (events.js:211:7)\n","stream":"stderr","time":"2019-05-13T15:14:20.460279536Z
    at addChunk (_stream_readable.js:263:12)\n","stream":"stderr","time":"2019-05-13T15:14:20.460297556Z
    at readableAddChunk (_stream_readable.js:250:11)\n","stream":"stderr","time":"2019-05-13T15:14:20.460315365Z
    at Socket.Readable.push (_stream_readable.js:208:10)\n","stream":"stderr","time":"2019-05-13T15:14:20.460333175Z
    at TCP.onread (net.js:601:20)\n","stream":"stderr","time":"2019-05-13T15:14:20.460350915Z
     code: 'ER_NO_REFERENCED_ROW_2',\n","stream":"stderr","time":"2019-05-13T15:14:20.460368516Z
     errno: 1452,\n","stream":"stderr","time":"2019-05-13T15:14:20.460386256Z
     sqlState: '23000',\n","stream":"stderr","time":"2019-05-13T15:14:20.460404065Z
     sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`idm`.`role_assignment`, CONSTRAINT `role_assignment_ibfk_4` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE)',\n","stream":"stderr","time":"2019-05-13T15:14:20.460421735Z
     sql: 'INSERT INTO `role_assignment` (`id`,`role_id`,`user_id`,`oauth_client_id`) VALUES (DEFAULT,\\'provider\\',\\'admin\\',\\'c5b79180-ca92-4a23-9e33-11edcfe486ae\\');' },\n","stream":"stderr","time":"2019-05-13T15:14:20.460451628Z
  original: \n","stream":"stderr","time":"2019-05-13T15:14:20.460470835Z
   { Error: Cannot add or update a child row: a foreign key constraint fails (`idm`.`role_assignment`, CONSTRAINT `role_assignment_ibfk_4` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE)\n","stream":"stderr","time":"2019-05-13T15:14:20.460488575Z
    at Packet.asError (/opt/fiware-idm/node_modules/mysql2/lib/packets/packet.js:684:17)\n","stream":"stderr","time":"2019-05-13T15:14:20.460507642Z
    at Query.execute (/opt/fiware-idm/node_modules/mysql2/lib/commands/command.js:28:26)\n","stream":"stderr","time":"2019-05-13T15:14:20.460525801Z
    at Connection.handlePacket (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:455:32)\n","stream":"stderr","time":"2019-05-13T15:14:20.46054375Z
    at PacketParser.onPacket (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:73:18)\n","stream":"stderr","time":"2019-05-13T15:14:20.460561769Z
    at PacketParser.executeStart (/opt/fiware-idm/node_modules/mysql2/lib/packet_parser.js:75:16)\n","stream":"stderr","time":"2019-05-13T15:14:20.460579719Z
    at Socket.\u003canonymous\u003e (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:80:31)\n","stream":"stderr","time":"2019-05-13T15:14:20.460597668Z
    at emitOne (events.js:116:13)\n","stream":"stderr","time":"2019-05-13T15:14:20.460615339Z
    at Socket.emit (events.js:211:7)\n","stream":"stderr","time":"2019-05-13T15:14:20.460631332Z
    at addChunk (_stream_readable.js:263:12)\n","stream":"stderr","time":"2019-05-13T15:14:20.460648374Z
    at readableAddChunk (_stream_readable.js:250:11)\n","stream":"stderr","time":"2019-05-13T15:14:20.460665974Z
    at Socket.Readable.push (_stream_readable.js:208:10)\n","stream":"stderr","time":"2019-05-13T15:14:20.460683575Z
    at TCP.onread (net.js:601:20)\n","stream":"stderr","time":"2019-05-13T15:14:20.460701175Z
     code: 'ER_NO_REFERENCED_ROW_2',\n","stream":"stderr","time":"2019-05-13T15:14:20.460718635Z
     errno: 1452,\n","stream":"stderr","time":"2019-05-13T15:14:20.460735677Z
     sqlState: '23000',\n","stream":"stderr","time":"2019-05-13T15:14:20.460753138Z
     sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`idm`.`role_assignment`, CONSTRAINT `role_assignment_ibfk_4` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE)',\n","stream":"stderr","time":"2019-05-13T15:14:20.460770598Z
     sql: 'INSERT INTO `role_assignment` (`id`,`role_id`,`user_id`,`oauth_client_id`) VALUES (DEFAULT,\\'provider\\',\\'admin\\',\\'c5b79180-ca92-4a23-9e33-11edcfe486ae\\');' },\n","stream":"stderr","time":"2019-05-13T15:14:20.460791481Z
  sql: 'INSERT INTO `role_assignment` (`id`,`role_id`,`user_id`,`oauth_client_id`) VALUES (DEFAULT,\\'provider\\',\\'admin\\',\\'c5b79180-ca92-4a23-9e33-11edcfe486ae\\');',\n","stream":"stderr","time":"2019-05-13T15:14:20.460811246Z
  fields: [ 'user_id' ],\n","stream":"stderr","time":"2019-05-13T15:14:20.460830244Z
  table: 'user',\n","stream":"stderr","time":"2019-05-13T15:14:20.460847914Z
  value: 'admin',\n","stream":"stderr","time":"2019-05-13T15:14:20.460865304Z
  index: 'role_assignment_ibfk_4',\n","stream":"stderr","time":"2019-05-13T15:14:20.460881857Z
  reltype: 'child' }\n","stream":"stderr","time":"2019-05-13T15:14:20.46089848Z
(node:253) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined\n","stream":"stderr","time":"2019-05-13T15:14:20.460915312Z
    at /opt/fiware-idm/controllers/web/applications.js:497:26\n","stream":"stderr","time":"2019-05-13T15:14:20.46093354Z
    at \u003canonymous\u003e\n","stream":"stderr","time":"2019-05-13T15:14:20.4609605Z
(node:253) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)\n","stream":"stderr","time":"2019-05-13T15:14:20.460979147Z
```

**Comment by jason-fox** [comment]
Within the [startContainers()](https://github.com/FIWARE/tutorials.XACML-Access-Rules/blob/master/services#L33-L38) section of the `services` script it is doing more than just `docker-compose up` - it could be that the `IDM_HTTPS_ENABLED` needs setting a previous installation has left something running from a previous start which is incompatible with the start up.

If you must us `docker-compose` directly, please check what you have running using `docker ps` and kill any remaining images. Sometimes I need to `docker system prune` or `docker volume prune` or `docker network prune` to start from a clean state.

The `services` script does what it can and hence is the preferred option on start-up according to the documentation. I would try using that rather than `docker-compose up -d` which could lead to an unexpected state.

**Comment by tmontanaro** [comment]
Ok, if I run the tutorial through the services script this error does not appear.
So maybe it was related to the preliminary actions that the script performs before running the containers.
