### ISSUE TITLE
services "Error in IDM communication" when trying to contact Orion through the PEP Proxy

### ISSUE THREAD

**Issue by tmontanaro** [FIWARE/tutorials.XACML-Access-Rules#5]
If I run everything through the services script I obtain the following error:

"Error in IDM communication" when trying to contact Orion through the PEP Proxy by passing the generated token.
I tried to restar the IdM and, then the PeP Proxy but nothing changed.

Maybe it is connected to issue #2 (which error is generated when I try to run all the containers without using the "services" script)

**Comment by jason-fox** [comment]
Yes it will be connected to #2  - `"Error in IDM communication"` is a standard PEP Proxy [error message](https://github.com/ging/fiware-pep-proxy/blob/master/controllers/root.js#L163-L164) when communications cannot occur. Since the other issue means that Keyrock is not accessible, the PEP Proxy is denying access.

**Comment by jason-fox** [comment]
Closing as duplicate/related to #2

**Comment by tmontanaro** [comment]
Unfortunately, it is another bug, not related to #2.
If, in fact, I run the tutorial through the script "services" (docker-compose version: 1.24.0, build 0aa59064) and I look into the logs of the `fiware-orion-proxy` container, I find the following:
```
2019-05-15 09:38:13.348  - INFO: Server - Starting PEP proxy in port 1027. IdM authentication ...
2019-05-15 09:38:13.387  - ERROR: Server - Error in IDM communication Error: connect ECONNREFUSED 172.18.1.5:3005
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
2019-05-15 09:38:13.387  - INFO: Server - Waiting 5 seconds before attempting again.
2019-05-15 09:38:18.396  - ERROR: Server - Error in IDM communication Error: connect ECONNREFUSED 172.18.1.5:3005
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
2019-05-15 09:38:18.397  - INFO: Server - Waiting 5 seconds before attempting again.
2019-05-15 09:38:23.401  - ERROR: Server - Error in IDM communication Error: connect ECONNREFUSED 172.18.1.5:3005
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
2019-05-15 09:38:23.401  - INFO: Server - Waiting 5 seconds before attempting again.
2019-05-15 09:38:28.405  - ERROR: Server - Error in IDM communication Error: connect ECONNREFUSED 172.18.1.5:3005
```
